<?php
    require_once "chaves.php";
    //funcao q retorna hoteis com os seguintes parametros
    //exemplo de data de chegada: 2016-06-21T12:00:00Z ->YYYY-MM-DDTHH:mm:ssZ
    function procuraHotel($pais, $cidade, $dataChegada, $numeroNoites){
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, 'https://api.ba.com/rest-v1/v1/hotels;countryCode='.$pais.';
        cityCode='.$cidade.';checkInDate='.$dataChegada.';numberOfNights='.$numeroNoites.';format=.json');
        curl_setopt($ch, CURLOPT_HTTPHEADER, array('Client-Key: '.$chaveHotel));//ESSA CHAVE NAO É MINHA, USEM COM CUIDADO
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true); 
        
        $result = curl_exec($ch);
        curl_close($ch);
        return $result;//um json gigante
    }
    
    //funcao q retorna exemplo de resposta do procuraHotel
    function hoteis(){
        $retorno = '{
            "HotelSearchResponse": {
                "HotelSearch": [{
                    "BoardBasis": "Continental breakfast",
                    "CurrencyCode": "US",
                    "DeepLink": "http:\/\/www.ba.com\/travel\/fx\/public\/en_NL\/pCode1-US-SFO-5631234\/?saleOption=HO&hotelGOTo=SFO&ojDd=CITY_SFO_CA_US&ojGw=SFO&checkInGO=21\/06\/16&checkOutGO=22\/06\/16&numNightsGO=1&roomsRqd=1&adultsRoom1=2&childrenRoom1=0&infantsRoom1=0&eId=111077&totalPrice=770&currencyCode=EUR",
                    "HotelCheckInDate": "2016-06-21T12:00:00Z",
                    "HotelCheckOutDate": "2016-06-21T12:00:00Z",
                    "HotelCity": "Fisherman\'s Wharf",
                    "HotelCityCode": "SFO",
                    "HotelDescription": "This outstanding San Francisco luxury hotel offers the best of both worlds such as a perfect locale with exceptional services for their guests. Take advantage of all they have to offer, including plush new Grand Beds, award-winning bar, complete business amenities and beautiful event spaces.\n\nThe ideal setting in Fisherman&apos;s Wharf allows guests to enjoy all of this area&apos;s vibrant attractions, just steps from this luxury hotel in San Francisco, California. Stroll along Pier 39, sample delicious fare at Ghirardelli Square, or hop on a cable car just across the street. From onsite expert meeting planners to the knowledgeable and attentive concierge, their professional staff is always on hand to assist you in making your stay as flawless as possible.\n\nKnuckles at the Wharf offers the charming atmosphere of a full-service restaurant that beckons you to sit back, relax, and enjoy classic American favorite dishes. Walls of windows, in this turn-of-the-century brick building, pour rays of sunshine onto the guests inside. Get your day off to a perfect start with an invigorating cup of freshly brewed Starbucks coffee and one of their signature breakfast items. Join colleagues for a working lunch, or plan the next day&apos;s events over dinner in Knuckles; the expansive menu offers a variety of dishes to please any pallet.",
                    "HotelID": "US-SFO-5631234",
                    "HotelImage": "http:\/\/www.britishairways.com\/badp\/static\/external\/US-SFO-5631234\/tn_11_US-SFO-5631234-B1553577131.jpeg",
                    "HotelName": "Hyatt Centric Fisherman\'s Wharf",
                    "HotelStarRating": 4,
                    "tripAdvisorGIFURL": "http:\/\/www.tripadvisor.co.uk\/img\/cdsi\/img2\/ratings\/traveler\/4.0-11576-4.png",
                    "tripAdvisorHotelName": "Hyatt Centric Fisherman&apos;s Wharf San Francisco",
                    "tripAdvisorPartnerID": "US-SFO-5631234",
                    "tripAdvisorRating": 4,
                    "tripAdvisorReviewCount": 435,
                    "tripAdvisorReviewURL": "http:\/\/www.tripadvisor.com\/Hotel_Review-g60713-d81087-Reviews-m11576-Hyatt_Centric_Fisherman_s_Wharf_San_Francisco-San_Francisco_California.html",
                    "isAirportHotel": false,
                    "isPackageRateOnly": false,
                    "Market": "NL",
                    "NumberOfNights": 1,
                    "PricePerPersonPerNight": 385,
                    "RoundedHotelStarRating": 4,
                    "TotalPrice": 770
                }, {
                    "BoardBasis": "Continental breakfast",
                    "CurrencyCode": "US",
                    "DeepLink": "http:\/\/www.ba.com\/travel\/fx\/public\/en_NL\/pCode1-US-SFO-5989000\/?saleOption=HO&hotelGOTo=SFO&ojDd=CITY_SFO_CA_US&ojGw=SFO&checkInGO=21\/06\/16&checkOutGO=22\/06\/16&numNightsGO=1&roomsRqd=1&adultsRoom1=2&childrenRoom1=0&infantsRoom1=0&eId=111077&totalPrice=828&currencyCode=EUR",
                    "HotelCheckInDate": "2016-06-21T12:00:00Z",
                    "HotelCheckOutDate": "2016-06-21T12:00:00Z",
                    "HotelCity": "RED WOOD CITY",
                    "HotelCityCode": "SFO",
                    "HotelDescription": "This hotel enjoys a convenient setting in San Francisco, lying just a short distance away from the airport, and boasting ease of access to the bay area of the city. This wonderful hotel lies within easy access of a host of attractions, as well as delightful dining options, stylish shopping opportunities and exciting entertainment venues. This wonderful hotel welcomes guests into a world of luxury and elegance. The guest rooms are beautifully designed, offering a cocoon of peace and serenity, in which to completely relax and unwind. The hotel features a wide range of exemplary facilities and services, meeting the needs of every type of traveller to a high level of excellence.",
                    "HotelID": "US-SFO-5989000",
                    "HotelImage": "http:\/\/www.britishairways.com\/badp\/static\/external\/US-SFO-5989000\/tn_14_US-SFO-5989000-H12861199001.jpeg",
                    "HotelName": "Sofitel San Francisco Bay",
                    "HotelStarRating": 5,
                    "tripAdvisorGIFURL": "http:\/\/www.tripadvisor.co.uk\/img\/cdsi\/img2\/ratings\/traveler\/4.0-11576-4.png",
                    "tripAdvisorHotelName": "Sofitel San Francisco Bay",
                    "tripAdvisorPartnerID": "US-SFO-5989000",
                    "tripAdvisorRating": 4,
                    "tripAdvisorReviewCount": 1182,
                    "tripAdvisorReviewURL": "http:\/\/www.tripadvisor.com\/Hotel_Review-g32956-d217295-Reviews-m11576-Sofitel_San_Francisco_Bay-Redwood_City_California.html",
                    "isAirportHotel": false,
                    "isPackageRateOnly": false,
                    "Market": "NL",
                    "NumberOfNights": 1,
                    "PricePerPersonPerNight": 414,
                    "RoundedHotelStarRating": 5,
                    "TotalPrice": 828
                }, {
                    "BoardBasis": "Room only",
                    "CurrencyCode": "US",
                    "DeepLink": "http:\/\/www.ba.com\/travel\/fx\/public\/en_NL\/pCode1-US-JMC-3394700\/?saleOption=HO&hotelGOTo=SFO&ojDd=CITY_SFO_CA_US&ojGw=SFO&checkInGO=21\/06\/16&checkOutGO=22\/06\/16&numNightsGO=1&roomsRqd=1&adultsRoom1=2&childrenRoom1=0&infantsRoom1=0&eId=111077&totalPrice=403.52&currencyCode=EUR",
                    "HotelCheckInDate": "2016-06-21T12:00:00Z",
                    "HotelCheckOutDate": "2016-06-21T12:00:00Z",
                    "HotelCity": "Sausalito",
                    "HotelCityCode": "SFO",
                    "HotelDescription": "Description: Cavallo Point in California, sister property to Big Sur&apos;s Post Ranch Inn, is a historic boutique hotel spread across old officers quarters and solar-panelled new builds just south of the shops and seafood of Sausalito.\n\n\n",
                    "HotelID": "US-JMC-3394700",
                    "HotelImage": "http:\/\/www.britishairways.com\/badp\/static\/external\/US-JMC-3394700\/tn_201_US-JMC-3394700-MK294664069.jpeg",
                    "HotelName": "Cavallo Point",
                    "HotelStarRating": 4.5,
                    "tripAdvisorGIFURL": "http:\/\/www.tripadvisor.co.uk\/img\/cdsi\/img2\/ratings\/traveler\/4.5-11576-4.png",
                    "tripAdvisorHotelName": "Cavallo Point",
                    "tripAdvisorPartnerID": "US-JMC-3394700",
                    "tripAdvisorRating": 4.5,
                    "tripAdvisorReviewCount": 837,
                    "tripAdvisorReviewURL": "http:\/\/www.tripadvisor.com\/Hotel_Review-g33062-d1019362-Reviews-m11576-Cavallo_Point-Sausalito_Marin_County_California.html",
                    "isAirportHotel": false,
                    "isPackageRateOnly": false,
                    "Market": "NL",
                    "NumberOfNights": 1,
                    "PricePerPersonPerNight": 202,
                    "RoundedHotelStarRating": 4,
                    "TotalPrice": 403.52
                }, {
                    "BoardBasis": "Room only",
                    "CurrencyCode": "US",
                    "DeepLink": "http:\/\/www.ba.com\/travel\/fx\/public\/en_NL\/pCode1-US-SFO-2689900\/?saleOption=HO&hotelGOTo=SFO&ojDd=CITY_SFO_CA_US&ojGw=SFO&checkInGO=21\/06\/16&checkOutGO=22\/06\/16&numNightsGO=1&roomsRqd=1&adultsRoom1=2&childrenRoom1=0&infantsRoom1=0&eId=111077&totalPrice=1596&currencyCode=EUR",
                    "HotelCheckInDate": "2016-06-21T12:00:00Z",
                    "HotelCheckOutDate": "2016-06-21T12:00:00Z",
                    "HotelCity": "San Francisco",
                    "HotelCityCode": "SFO",
                    "HotelDescription": "At Fairmont Heritage Place, Ghirardelli Square, these offerings allow you to step into a timeless treasure, a European-inspired enclave with the pulse of an intimate piazza. Overlooking the San Francisco Bay, Fairmont Heritage Place Ghirardelli Square is a bold illustration of contemporary urban design in a landmark setting.\n\nThe cornerstone of Ghirardelli Square, Ghirardelli&apos;s illustrious chocolate factory, has been reinvented as Fairmont Heritage Place, Ghirardelli Square. These San Francisco residences allow you to experience one of the city&apos;s most precious jewels in a new and intimate way.\n\nOffering one, two, and three bedroom luxury residences in San Francisco, Fairmont Heritage Place, Ghirardelli Square affords you all the comforts of home with the world class service of Fairmont that today&apos;s discerning travelers have come to expect.",
                    "HotelID": "US-SFO-2689900",
                    "HotelImage": "http:\/\/www.britishairways.com\/badp\/static\/external\/US-SFO-2689900\/tn_11_US-SFO-2689900-B13373882450.jpeg",
                    "HotelName": "Fairmont Heritage Place, Ghirardelli Square",
                    "HotelStarRating": 5,
                    "tripAdvisorGIFURL": "http:\/\/www.tripadvisor.co.uk\/img\/cdsi\/img2\/ratings\/traveler\/4.5-11576-4.png",
                    "tripAdvisorHotelName": "Fairmont Heritage Place, Ghirardelli Square",
                    "tripAdvisorPartnerID": "US-SFO-2689900",
                    "tripAdvisorRating": 4.5,
                    "tripAdvisorReviewCount": 589,
                    "tripAdvisorReviewURL": "http:\/\/www.tripadvisor.com\/Hotel_Review-g60713-d1175274-Reviews-m11576-Fairmont_Heritage_Place_Ghirardelli_Square-San_Francisco_California.html",
                    "isAirportHotel": false,
                    "isPackageRateOnly": false,
                    "Market": "NL",
                    "NumberOfNights": 1,
                    "PricePerPersonPerNight": 798,
                    "RoundedHotelStarRating": 5,
                    "TotalPrice": 1596
                }, {
                    "BoardBasis": "Room only",
                    "CurrencyCode": "US",
                    "DeepLink": "http:\/\/www.ba.com\/travel\/fx\/public\/en_NL\/pCode1-US-SFO-4874868\/?saleOption=HO&hotelGOTo=SFO&ojDd=CITY_SFO_CA_US&ojGw=SFO&checkInGO=21\/06\/16&checkOutGO=22\/06\/16&numNightsGO=1&roomsRqd=1&adultsRoom1=2&childrenRoom1=0&infantsRoom1=0&eId=111077&totalPrice=510&currencyCode=EUR",
                    "HotelCheckInDate": "2016-06-21T12:00:00Z",
                    "HotelCheckOutDate": "2016-06-21T12:00:00Z",
                    "HotelCity": "Civic Centre",
                    "HotelCityCode": "SFO",
                    "HotelDescription": "This historic hotel highlights turn-of-the-century architecture, creating an elegant and sophisticated ambience. It is located on bustling Market Street.\n\nThe lovely interiors and cathedral high ceilings give Whitcomb an elegant boutique feel. The historic lobby is grand and spectacular, with marble pillars, Tiffany glass and hand-carved wood.\n\nAfter the 1906 earthquake ruined the city, the hotel served as San Francisco&apos;s City Hall from 1912 to 1915.\n\nThe Whitcomb is set on vibrant Market Street, across from the Orpheum Theatre and the Asian Art Museum. The cruises, China Town and tourist activities such as Alcatraz, as well as San Francisco Bay, are about a mile away.\n\nThe 460 guestrooms and 12 suites offer modern amenities and exceptional value. They enjoy chic decor and custom fabrics, also featuring a luxurious menu of Judith Jackson Spa amenities. The hotel&apos;s facilities also include a spa.",
                    "HotelID": "US-SFO-4874868",
                    "HotelImage": "http:\/\/www.britishairways.com\/badp\/static\/external\/US-SFO-4874868\/tn_17_US-SFO-4874868-H11509953911.jpeg",
                    "HotelName": "Whitcomb",
                    "HotelStarRating": 3,
                    "tripAdvisorGIFURL": "http:\/\/www.tripadvisor.co.uk\/img\/cdsi\/img2\/ratings\/traveler\/3.5-11576-4.png",
                    "tripAdvisorHotelName": "Hotel Whitcomb",
                    "tripAdvisorPartnerID": "US-SFO-4874868",
                    "tripAdvisorRating": 3.5,
                    "tripAdvisorReviewCount": 2428,
                    "tripAdvisorReviewURL": "http:\/\/www.tripadvisor.com\/Hotel_Review-g60713-d81241-Reviews-m11576-Hotel_Whitcomb-San_Francisco_California.html",
                    "isAirportHotel": false,
                    "isPackageRateOnly": false,
                    "Market": "NL",
                    "NumberOfNights": 1,
                    "PricePerPersonPerNight": 255,
                    "RoundedHotelStarRating": 3,
                    "TotalPrice": 510
                }, {
                    "BoardBasis": "Room only",
                    "CurrencyCode": "US",
                    "DeepLink": "http:\/\/www.ba.com\/travel\/fx\/public\/en_NL\/pCode1-US-SFO-7719000\/?saleOption=HO&hotelGOTo=SFO&ojDd=CITY_SFO_CA_US&ojGw=SFO&checkInGO=21\/06\/16&checkOutGO=22\/06\/16&numNightsGO=1&roomsRqd=1&adultsRoom1=2&childrenRoom1=0&infantsRoom1=0&eId=111077&totalPrice=509&currencyCode=EUR",
                    "HotelCheckInDate": "2016-06-21T12:00:00Z",
                    "HotelCheckOutDate": "2016-06-21T12:00:00Z",
                    "HotelCity": "San Francisco",
                    "HotelCityCode": "SFO",
                    "HotelDescription": "Just two blocks from the bay and one block from the Hyde Cable Car, this hotel enjoys an ideal location. Its family friendly atmosphere is enhanced by good value children&apos;s meals, a children&apos;s pool and onsite laundry. \r\rA 24-hour restaurant is useful for travellers with awkward flight or travel times.",
                    "HotelID": "US-SFO-7719000",
                    "HotelImage": "http:\/\/www.britishairways.com\/badp\/static\/external\/US-SFO-7719000\/tn_11_US-SFO-7719000-HTLHIF-H1301.jpeg",
                    "HotelName": "Holiday Inn Fishermans Wharf",
                    "HotelStarRating": 3,
                    "tripAdvisorGIFURL": "http:\/\/www.tripadvisor.co.uk\/img\/cdsi\/img2\/ratings\/traveler\/3.5-11576-4.png",
                    "tripAdvisorHotelName": "Holiday Inn San Francisco Fishermans Wharf",
                    "tripAdvisorPartnerID": "US-SFO-7719000",
                    "tripAdvisorRating": 3.5,
                    "tripAdvisorReviewCount": 3172,
                    "tripAdvisorReviewURL": "http:\/\/www.tripadvisor.com\/Hotel_Review-g60713-d81042-Reviews-m11576-Holiday_Inn_San_Francisco_Fishermans_Wharf-San_Francisco_California.html",
                    "isAirportHotel": false,
                    "isPackageRateOnly": false,
                    "Market": "NL",
                    "NumberOfNights": 1,
                    "PricePerPersonPerNight": 255,
                    "RoundedHotelStarRating": 3,
                    "TotalPrice": 509
                }, {
                    "BoardBasis": "Room only",
                    "CurrencyCode": "US",
                    "DeepLink": "http:\/\/www.ba.com\/travel\/fx\/public\/en_NL\/pCode1-US-SFO-7725212\/?saleOption=HO&hotelGOTo=SFO&ojDd=CITY_SFO_CA_US&ojGw=SFO&checkInGO=21\/06\/16&checkOutGO=22\/06\/16&numNightsGO=1&roomsRqd=1&adultsRoom1=2&childrenRoom1=0&infantsRoom1=0&eId=111077&totalPrice=703&currencyCode=EUR",
                    "HotelCheckInDate": "2016-06-21T12:00:00Z",
                    "HotelCheckOutDate": "2016-06-21T12:00:00Z",
                    "HotelCity": "Nob Hill",
                    "HotelCityCode": "SFO",
                    "HotelDescription": "The Fairmont is situated where each of the cable car lines meet, offering impeccable service and panoramic views of the city and the bay from the top of Nob Hill.\n\nWith its central location this luxury hotel is a short cable car trip from the bustling Downtown financial district, Union Square and Fishermans Wharf. It occupies a landmark building dating back to 1907 and offers excellent levels of service and amenities.\n\nThe hotel&apos;s atmosphere is elegant and relaxing. It has 591 individually furnished and decorated rooms. Its 62 suites offer impressive views of the city and bay. In addition to the standard facilities, the rooms feature multi-line phones with voicemail and internet access.\n\nThe grandeur of the hotel coupled with its reputation for impeccable service promises a truly memorable service. It offers fine dining with three renowned restaurants and lounges, as well as 55,000 square feet of spectacular function space.",
                    "HotelID": "US-SFO-7725212",
                    "HotelImage": "http:\/\/www.britishairways.com\/badp\/static\/external\/US-SFO-7725212\/tn_11_US-SFO-7725212-HTLFSF-H1104.jpeg",
                    "HotelName": "Fairmont San Francisco",
                    "HotelStarRating": 5,
                    "tripAdvisorGIFURL": "http:\/\/www.tripadvisor.co.uk\/img\/cdsi\/img2\/ratings\/traveler\/4.5-11576-4.png",
                    "tripAdvisorHotelName": "The Fairmont San Francisco",
                    "tripAdvisorPartnerID": "US-SFO-7725212",
                    "tripAdvisorRating": 4.5,
                    "tripAdvisorReviewCount": 2029,
                    "tripAdvisorReviewURL": "http:\/\/www.tripadvisor.com\/Hotel_Review-g60713-d81397-Reviews-m11576-The_Fairmont_San_Francisco-San_Francisco_California.html",
                    "isAirportHotel": false,
                    "isPackageRateOnly": false,
                    "Market": "NL",
                    "NumberOfNights": 1,
                    "PricePerPersonPerNight": 352,
                    "RoundedHotelStarRating": 5,
                    "TotalPrice": 703
                }, {
                    "BoardBasis": "Full breakfast",
                    "CurrencyCode": "US",
                    "DeepLink": "http:\/\/www.ba.com\/travel\/fx\/public\/en_NL\/pCode1-US-SFO-4094600\/?saleOption=HO&hotelGOTo=SFO&ojDd=CITY_SFO_CA_US&ojGw=SFO&checkInGO=21\/06\/16&checkOutGO=22\/06\/16&numNightsGO=1&roomsRqd=1&adultsRoom1=2&childrenRoom1=0&infantsRoom1=0&eId=111077&totalPrice=585&currencyCode=EUR",
                    "HotelCheckInDate": "2016-06-21T12:00:00Z",
                    "HotelCheckOutDate": "2016-06-21T12:00:00Z",
                    "HotelCity": "Fisherman\'s Wharf",
                    "HotelCityCode": "SFO",
                    "HotelDescription": "This modern hotel is great value for money, making it an ideal alternative to Union Square. Enjoy a complimentary &apos;Express Start&apos; breakfast and free internet access in guest rooms. \n\nJust two blocks from the bay and one block from the Hyde Cable Car, this hotel enjoys a great location. It is a five-minute walk from Pier 39 and Alcatraz, close to many restaurants and family attractions. For shopping, take the tram along the Embarcadero to Market Street, where you can go on to Union Square and Chinatown.\n\nComplimentary local phone calls, fitness centre and a business area with use of computers and internet access are also available.",
                    "HotelID": "US-SFO-4094600",
                    "HotelImage": "http:\/\/www.britishairways.com\/badp\/static\/external\/US-SFO-4094600\/tn_11_US-SFO-4094600-HTLHIE-H1506.jpeg",
                    "HotelName": "Holiday Inn Express Fishermans Wharf",
                    "HotelStarRating": 3,
                    "tripAdvisorGIFURL": "http:\/\/www.tripadvisor.co.uk\/img\/cdsi\/img2\/ratings\/traveler\/4.0-11576-4.png",
                    "tripAdvisorHotelName": "Holiday Inn Express Hotel &amp; Suites San Francisco Fisherman&apos;s Wharf",
                    "tripAdvisorPartnerID": "US-SFO-4094600",
                    "tripAdvisorRating": 4,
                    "tripAdvisorReviewCount": 2167,
                    "tripAdvisorReviewURL": "http:\/\/www.tripadvisor.com\/Hotel_Review-g60713-d217813-Reviews-m11576-Holiday_Inn_Express_Hotel_Suites_San_Francisco_Fisherman_s_Wharf-San_Francisco_Ca.html",
                    "isAirportHotel": false,
                    "isPackageRateOnly": false,
                    "Market": "NL",
                    "NumberOfNights": 1,
                    "PricePerPersonPerNight": 293,
                    "RoundedHotelStarRating": 3,
                    "TotalPrice": 585
                }, {
                    "BoardBasis": "Room only",
                    "CurrencyCode": "US",
                    "DeepLink": "http:\/\/www.ba.com\/travel\/fx\/public\/en_NL\/pCode1-US-SFO-3923434\/?saleOption=HO&hotelGOTo=SFO&ojDd=CITY_SFO_CA_US&ojGw=SFO&checkInGO=21\/06\/16&checkOutGO=22\/06\/16&numNightsGO=1&roomsRqd=1&adultsRoom1=2&childrenRoom1=0&infantsRoom1=0&eId=111077&totalPrice=688&currencyCode=EUR",
                    "HotelCheckInDate": "2016-06-21T12:00:00Z",
                    "HotelCheckOutDate": "2016-06-21T12:00:00Z",
                    "HotelCity": "Nob Hill",
                    "HotelCityCode": "SFO",
                    "HotelDescription": "A Historic Grandeur on the crest of Nob Hill. As splendid now as when it opened to great fanfare in 1926, The InterContinental Mark Hopkins San Francisco is one of the city&apos;s finest hotels. Located at the crossing of three cable car lines, the venerable landmark is minutes from Union Square, Chinatown and the Financial District. Fisherman&apos;s Wharf and the Golden Gate Bridge are short drives away.\n\nThis Gothic hulk of a building is named after Mark Hopkins, the Central Pacific railroad co-founder whose mansion previously stood here. Nearly every room has a stunning view. Enjoy the ultimate perch above the city and feel like a railroad tycoon.\n\nJust when you think you&apos;ve seen the best of San Francisco&apos;s sights, the Top of the Mark will thrill you all over again. The legendary sky bar lays the city at your feet with near-360 degree vistas. Almost as famous as the view is the 100 Martinis menu, which features popular concoctions such as the Lychee Martini, the Lemon Drop and the 24 Karrot.",
                    "HotelID": "US-SFO-3923434",
                    "HotelImage": "http:\/\/www.britishairways.com\/badp\/static\/external\/US-SFO-3923434\/tn_11_US-SFO-3923434-B11282292373.jpeg",
                    "HotelName": "Intercontinental Mark Hopkins",
                    "HotelStarRating": 4,
                    "tripAdvisorGIFURL": "http:\/\/www.tripadvisor.co.uk\/img\/cdsi\/img2\/ratings\/traveler\/4.0-11576-4.png",
                    "tripAdvisorHotelName": "InterContinental Mark Hopkins San Francisco",
                    "tripAdvisorPartnerID": "US-SFO-3923434",
                    "tripAdvisorRating": 4,
                    "tripAdvisorReviewCount": 2130,
                    "tripAdvisorReviewURL": "http:\/\/www.tripadvisor.com\/Hotel_Review-g60713-d115623-Reviews-m11576-InterContinental_Mark_Hopkins_San_Francisco-San_Francisco_California.html",
                    "isAirportHotel": false,
                    "isPackageRateOnly": false,
                    "Market": "NL",
                    "NumberOfNights": 1,
                    "PricePerPersonPerNight": 344,
                    "RoundedHotelStarRating": 4,
                    "TotalPrice": 688
                }, {
                    "BoardBasis": "Room only",
                    "CurrencyCode": "US",
                    "DeepLink": "http:\/\/www.ba.com\/travel\/fx\/public\/en_NL\/pCode1-US-SFO-6779494\/?saleOption=HO&hotelGOTo=SFO&ojDd=CITY_SFO_CA_US&ojGw=SFO&checkInGO=21\/06\/16&checkOutGO=22\/06\/16&numNightsGO=1&roomsRqd=1&adultsRoom1=2&childrenRoom1=0&infantsRoom1=0&eId=111077&totalPrice=706&currencyCode=EUR",
                    "HotelCheckInDate": "2016-06-21T12:00:00Z",
                    "HotelCheckOutDate": "2016-06-21T12:00:00Z",
                    "HotelCity": "Financial District",
                    "HotelCityCode": "SFO",
                    "HotelDescription": "This beautiful hotel is located on Nob Hill, right on the cable car line and close to Union Square. Features include its award-winning steakhouse and health club.\n\nLocated in the heart of Downtown San Francisco, The Omni San Francisco Hotel provides luxury accommodation in a 17-storey building dating back to 1926. It is a short walk to Union Square, known for its high-end shopping and art galleries.\n\nWith Florentine architecture, this modern hotel has boutique ambiance and is ideal for a romantic getaway, the lobby is adorned with Italian marble, rich fabrics and Austrian crystal chandeliers.\n\nGuests may make use of the large health club with spa, and there is a kids club and welcome backpack for youngsters with the Sensational Kids programme. Enjoy the complimentary walking tour to explore the city. A golf course is located 3km away.",
                    "HotelID": "US-SFO-6779494",
                    "HotelImage": "http:\/\/www.britishairways.com\/badp\/static\/external\/US-SFO-6779494\/tn_61_US-SFO-6779494-HTLOSF-B1203.jpeg",
                    "HotelName": "Omni Hotel San Francisco",
                    "HotelStarRating": 4.5,
                    "tripAdvisorGIFURL": "http:\/\/www.tripadvisor.co.uk\/img\/cdsi\/img2\/ratings\/traveler\/4.5-11576-4.png",
                    "tripAdvisorHotelName": "Omni San Francisco Hotel",
                    "tripAdvisorPartnerID": "US-SFO-6779494",
                    "tripAdvisorRating": 4.5,
                    "tripAdvisorReviewCount": 4112,
                    "tripAdvisorReviewURL": "http:\/\/www.tripadvisor.com\/Hotel_Review-g60713-d224948-Reviews-m11576-Omni_San_Francisco_Hotel-San_Francisco_California.html",
                    "isAirportHotel": false,
                    "isPackageRateOnly": false,
                    "Market": "NL",
                    "NumberOfNights": 1,
                    "PricePerPersonPerNight": 353,
                    "RoundedHotelStarRating": 4,
                    "TotalPrice": 706
                }]
            }
        }'
        return $retorno;
    }
?>
